org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.daemon=true

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.8.6
maven_group=dev.darkness
archives_base_name=darkness-client-1.21.11
